### ISSUE TITLE
Can't pan (or too dumb to find out how)

### ISSUE THREAD

**Issue by aethernet** [au-re/ramen#24]
Hi, 

Thanks for this wonderful lib. 
Works very well until i try to pan.
I'm not been able to find out how to (or it's broken)

A little help would be very welcome (firefox 74.0 on macos 10.15.1)

**Comment by aethernet** [comment]
ok i just read the code (i should have started there) and middle click is basically unavailable on mac's trackpad.

So an alternative like alt+drag would be great.

I'll do a PR when i have something

**Comment by au-re** [comment]
Hi  @aethernet! yes indeed right now you can only pan with middle click. Ideally keybindings should become customizable but I'm not quite sure how to proceed there. I have to look a bit further what would be the best way to abstract this. I'm open to suggestions of course!

**Comment by au-re** [comment]
Maybe managing key maps with a library such as https://craig.is/killing/mice or https://github.com/piranha/keymage would work? I will try them out later today and see if I can find something that supports mouse inputs as well.

**Comment by au-re** [comment]
Added the following issues related to this:

#26 #27
